# Calculate average fps

In [1]:
f = open("fps.txt", "r")
total = 0
avg_fps = 0
for x in f:
    # print(int(x.strip()))
    total += float(x.strip())
avg_fps = total/2000
print(avg_fps) 

8.638140000000035


In [2]:
f = open("time.txt", "r")
total = 0
avg_time = 0
for x in f:
    # print(int(x.strip()))
    total += float(x.strip())
avg_time = total/2000
print(avg_time) 

115.76795000000016


In [1]:
import torch
torch.cuda.empty_cache()

In [ ]:
[[  ,        nan,        nan,  ..., 5.0272e-01, 8.2966e-01,
         1.0000e+00],
        [1.7195e+02, 4.0338e+02, 8.5830e+00,  ..., 6.0968e-01, 6.8277e-01,
         0.0000e+00]]

In [7]:
import torch
x = torch.tensor([1, 2, 3]).float()
x[x == 2] = float('nan')

print(x)

torch.nan_to_num(x, nan=0.0)
print(x)

tensor([1., nan, 3.])
tensor([1., nan, 3.])


In [23]:
x = torch.tensor([float('nan'), float('nan'), -float('nan'), 3.14])
print(x)
# y = torch.nan_to_num(x, nan=2.0)
y = torch.isnan(x).any()
if y == True:
    print('yes')

tensor([   nan,    nan,    nan, 3.1400])
yes


In [14]:
x = torch.tensor([float('1'), float('1'), -float('2'), 3.14])
print(x)
y = torch.nan_to_num(x, nan=2.0)
print(y)

tensor([ 1.0000,  1.0000, -2.0000,  3.1400])
tensor([ 1.0000,  1.0000, -2.0000,  3.1400])


In [19]:
import math
x = torch.tensor([float('nan'), float('1'), -float('2'), 3.14])
y = torch.isnan(x)
if y == True:
    print("yes")

RuntimeError: Boolean value of Tensor with more than one value is ambiguous